// Datos de tarjetas de chino para el set interactivo (HSK 1)
const cardsData = [
    {
        character: "我",
        image: "../images-chosen-chinese/我.png",
        pinyin: "wǒ",
        meaning: "Yo",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "我是学生。",
        phrasePinyin: "Wǒ shì xuésheng.",
        phraseEs: "Yo soy estudiante.",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "你",
        image: "../images-chosen-chinese/你.png",
        pinyin: "nǐ",
        meaning: "Tú",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "你好吗？",
        phrasePinyin: "Nǐ hǎo ma?",
        phraseEs: "¿Cómo estás?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "他",
        image: "../images-chosen-chinese/他.png",
        pinyin: "tā",
        meaning: "Él",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "他是我的老师。",
        phrasePinyin: "Tā shì wǒ de lǎoshī.",
        phraseEs: "Él es mi profesor.",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "她",
        image: "../images-chosen-chinese/她.png",
        pinyin: "tā",
        meaning: "Ella",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "她在医院工作。",
        phrasePinyin: "Tā zài yīyuàn gōngzuò.",
        phraseEs: "Ella trabaja en el hospital.",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "我们",
        image: "../images-chosen-chinese/我们.png",
        pinyin: "wǒmen",
        meaning: "Nosotros",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "我们都喜欢看电影。",
        phrasePinyin: "Wǒmen dōu xǐhuan kàn diànyǐng.",
        phraseEs: "A todos nosotros nos gusta ver películas.",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "这",
        image: "../images-chosen-chinese/这.png",
        pinyin: "zhè",
        meaning: "Este",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "这是我的书。",
        phrasePinyin: "Zhè shì wǒ de shū.",
        phraseEs: "Este es mi libro.",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "那",
        image: "../images-chosen-chinese/那.png",
        pinyin: "nà",
        meaning: "Ese",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "那是谁的电脑？",
        phrasePinyin: "Nà shì shéi de diànnǎo?",
        phraseEs: "¿De quién es ese ordenador?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "哪",
        image: "../images-chosen-chinese/哪.png",
        pinyin: "nǎ",
        meaning: "Cuál",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "你是哪国人？",
        phrasePinyin: "Nǐ shì nǎ guó rén?",
        phraseEs: "¿De qué país eres?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "哪儿",
        image: "../images-chosen-chinese/哪儿.png",
        pinyin: "nǎr",
        meaning: "Dónde",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "你要去哪儿？",
        phrasePinyin: "Nǐ yào qù nǎr?",
        phraseEs: "¿Adónde vas a ir?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "谁",
        image: "../images-chosen-chinese/谁.png",
        pinyin: "shéi",
        meaning: "Quién",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "谁是你的朋友？",
        phrasePinyin: "Shéi shì nǐ de péngyou?",
        phraseEs: "¿Quién es tu amigo?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "什么",
        image: "../images-chosen-chinese/什么.png",
        pinyin: "shénme",
        meaning: "Qué",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "这是什么东西？",
        phrasePinyin: "Zhè shì shénme dōngxi?",
        phraseEs: "¿Qué cosa es esto?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "多少",
        image: "../images-chosen-chinese/多少.png",
        pinyin: "duōshǎo",
        meaning: "Cuánto",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "这个杯子多少钱？",
        phrasePinyin: "Zhège bēizi duōshǎo qián?",
        phraseEs: "¿Cuánto cuesta esta taza?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "几",
        image: "../images-chosen-chinese/几.png",
        pinyin: "jǐ",
        meaning: "Cuántos",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "你家里有几个人？",
        phrasePinyin: "Nǐ jiā lǐ yǒu jǐ gè rén?",
        phraseEs: "¿Cuántas personas hay en tu casa?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "怎么",
        image: "../images-chosen-chinese/怎么.png",
        pinyin: "zěnme",
        meaning: "Cómo",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "这个字怎么读？",
        phrasePinyin: "Zhège zì zěnme dú?",
        phraseEs: "¿Cómo se lee este carácter?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "怎么样",
        image: "../images-chosen-chinese/怎么样.png",
        pinyin: "zěnmeyàng",
        meaning: "Qué tal",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "天气怎么样？",
        phrasePinyin: "Tiānqì zěnmeyàng?",
        phraseEs: "¿Qué tal está el tiempo?",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "每",
        image: "../images-chosen-chinese/每.png",
        pinyin: "měi",
        meaning: "Cada",
        type: "Pronombre",
        level: "HSK 1",
        phraseCn: "我每天六点起床。",
        phrasePinyin: "Wǒ měitiān liù diǎn qǐchuáng.",
        phraseEs: "Me levanto a las seis todos los días.",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "是",
        image: "../images-chosen-chinese/是.png",
        pinyin: "shì",
        meaning: "Ser",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我是学生。",
        phrasePinyin: "Wǒ shì xuésheng.",
        phraseEs: "Yo soy estudiante.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "有",
        image: "../images-chosen-chinese/有.png",
        pinyin: "yǒu",
        meaning: "Tener",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "桌子上有一本书。",
        phrasePinyin: "Zhuōzi shàng yǒu yī běn shū.",
        phraseEs: "Hay un libro sobre la mesa.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "看",
        image: "../images-chosen-chinese/看.png",
        pinyin: "kàn",
        meaning: "VER / LEER",
        type: "Verbo",
        level: "HSK 1",
        strokeCount: 9,
        radical: "目 (Ojo)",
        phraseCn: "我喜欢看电影。",
        phrasePinyin: "Wǒ xǐhuan kàn diànyǐng.",
        phraseEs: "Me gusta ver películas.",
        colorTheme: "from-rose-500 to-red-600"
    },
    {
        character: "听",
        image: "../images-chosen-chinese/听.png",
        pinyin: "tīng",
        meaning: "Escuchar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "你听，谁在说话？",
        phrasePinyin: "Nǐ tīng, shéi zài shuōhuà?",
        phraseEs: "Escucha, ¿quién está hablando?",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "说话",
        image: "../images-chosen-chinese/说话.png",
        pinyin: "shuōhuà",
        meaning: "Hablar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "请不要说话。",
        phrasePinyin: "Qǐng bùyào shuōhuà.",
        phraseEs: "Por favor, no habléis.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "读",
        image: "../images-chosen-chinese/读.png",
        pinyin: "dú",
        meaning: "Leer",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "你会读这个字吗？",
        phrasePinyin: "Nǐ huì dú zhège zì ma?",
        phraseEs: "¿Sabes leer este carácter?",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "写",
        image: "../images-chosen-chinese/写.png",
        pinyin: "xiě",
        meaning: "Escribir",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "他在写汉字。",
        phrasePinyin: "Tā zài xiě Hànzì.",
        phraseEs: "Él está escribiendo caracteres chinos.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "看见",
        image: "../images-chosen-chinese/看见.png",
        pinyin: "kànjiàn",
        meaning: "Ver",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我在商店看见了老师。",
        phrasePinyin: "Wǒ zài shāngdiàn kànjiàn le lǎoshī.",
        phraseEs: "He visto al profesor en la tienda.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "叫",
        image: "../images-chosen-chinese/叫.png",
        pinyin: "jiào",
        meaning: "Llamarse",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我叫大卫。",
        phrasePinyin: "Wǒ jiào Dàwèi.",
        phraseEs: "Me llamo David.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "来",
        image: "../images-chosen-chinese/来.png",
        pinyin: "lái",
        meaning: "Venir",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "请来我家里玩。",
        phrasePinyin: "Qǐng lái wǒ jiā lǐ wán.",
        phraseEs: "Por favor, ven a mi casa a pasar el rato.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "回",
        image: "../images-chosen-chinese/回.png",
        pinyin: "huí",
        meaning: "Volver",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我下午四点回家。",
        phrasePinyin: "Wǒ xiàwǔ sì diǎn huí jiā.",
        phraseEs: "Vuelvo a casa a las cuatro de la tarde.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "去",
        image: "../images-chosen-chinese/去.png",
        pinyin: "qù",
        meaning: "Ir",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我们去北京旅游。",
        phrasePinyin: "Wǒmen qù Běijīng lǚyóu.",
        phraseEs: "Vamos a ir a Pekín de viaje.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "吃",
        image: "../images-chosen-chinese/吃.png",
        pinyin: "chī",
        meaning: "COMER",
        type: "Verbo",
        level: "HSK 1",
        strokeCount: 6,
        radical: "口 (Boca)",
        phraseCn: "你喜欢吃什么菜？",
        phrasePinyin: "Nǐ xǐhuan chī shénme cài?",
        phraseEs: "¿Qué comida te gusta comer?",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "喝",
        image: "../images-chosen-chinese/喝.png",
        pinyin: "hē",
        meaning: "Beber",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我想喝一杯茶。",
        phrasePinyin: "Wǒ xiǎng hē yī bēi chá.",
        phraseEs: "Quiero beber una taza de té.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "睡觉",
        image: "../images-chosen-chinese/睡觉.png",
        pinyin: "shuìjiào",
        meaning: "Dormir",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "孩子在房间里睡觉。",
        phrasePinyin: "Háizi zài fángjiān lǐ shuìjiào.",
        phraseEs: "El niño está durmiendo en la habitación.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "做",
        image: "../images-chosen-chinese/做.png",
        pinyin: "zuò",
        meaning: "Hacer",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "你妈妈在做什么菜？",
        phrasePinyin: "Nǐ māma zài zuò shénme cài?",
        phraseEs: "¿Qué plato está cocinando tu madre?",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "买",
        image: "../images-chosen-chinese/买.png",
        pinyin: "mǎi",
        meaning: "Comprar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我想买衣服。",
        phrasePinyin: "Wǒ xiǎng mǎi yīfu.",
        phraseEs: "Quiero comprar ropa.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "开",
        image: "../images-chosen-chinese/开.png",
        pinyin: "kāi",
        meaning: "Abrir",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "他在开车。",
        phrasePinyin: "Tā zài kāichē.",
        phraseEs: "Él está conduciendo un coche.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "坐",
        image: "../images-chosen-chinese/坐.png",
        pinyin: "zuò",
        meaning: "Sentarse",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "请坐，请喝茶。",
        phrasePinyin: "Qǐng zuò, qǐng hē chá.",
        phraseEs: "Por favor siéntate, bebe té por favor.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "住",
        image: "../images-chosen-chinese/住.png",
        pinyin: "zhù",
        meaning: "Vivir",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "你住在哪里？",
        phrasePinyin: "Nǐ zhù zài nǎlǐ?",
        phraseEs: "¿Dónde vives?",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "学习",
        image: "../images-chosen-chinese/学习.png",
        pinyin: "xuéxí",
        meaning: "Estudiar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我在大学学习汉语。",
        phrasePinyin: "Wǒ zài dàxué xuéxí Hànyǔ.",
        phraseEs: "Estudio chino en la universidad.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "工作",
        image: "../images-chosen-chinese/工作.png",
        pinyin: "gōngzuò",
        meaning: "Trabajar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "他在医院工作。",
        phrasePinyin: "Tā zài yīyuàn gōngzuò.",
        phraseEs: "Él trabaja en un hospital.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "下雨",
        image: "../images-chosen-chinese/下雨.png",
        pinyin: "xiàyǔ",
        meaning: "Llover",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "外面在下雨。",
        phrasePinyin: "Wàimiàn zài xiàyǔ.",
        phraseEs: "Está lloviendo afuera.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "爱",
        image: "../images-chosen-chinese/爱.png",
        pinyin: "ài",
        meaning: "Amar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我爱我的妈妈。",
        phrasePinyin: "Wǒ ài wǒ de māma.",
        phraseEs: "Amo a mi madre.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "喜欢",
        image: "../images-chosen-chinese/喜欢.png",
        pinyin: "xǐhuan",
        meaning: "Gustar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我喜欢吃中国菜。",
        phrasePinyin: "Wǒ xǐhuan chī Zhōngguó cài.",
        phraseEs: "Me gusta comer comida china.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "想",
        image: "../images-chosen-chinese/想.png",
        pinyin: "xiǎng",
        meaning: "Querer",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我想去商店买东西。",
        phrasePinyin: "Wǒ xiǎng qù shāngdiàn mǎi dōngxi.",
        phraseEs: "Quiero ir a la tienda a comprar cosas.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "认识",
        image: "../images-chosen-chinese/认识.png",
        pinyin: "rènshi",
        meaning: "Conocer",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "很高兴认识你。",
        phrasePinyin: "Hěn gāoxìng rènshi nǐ.",
        phraseEs: "Mucho gusto en conocerte.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "会",
        image: "../images-chosen-chinese/会.png",
        pinyin: "huì",
        meaning: "Saber",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我会说一点儿汉语。",
        phrasePinyin: "Wǒ huì shuō yīdiǎnr Hànyǔ.",
        phraseEs: "Sé hablar un poco de chino.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "能",
        image: "../images-chosen-chinese/能.png",
        pinyin: "néng",
        meaning: "Poder",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "我今天不能去学校。",
        phrasePinyin: "Wǒ jīntiān bù néng qù xuéxiào.",
        phraseEs: "Hoy no puedo ir a la escuela.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "请",
        image: "../images-chosen-chinese/请.png",
        pinyin: "qǐng",
        meaning: "Por favor",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "请进，请坐。",
        phrasePinyin: "Qǐng jìn, qǐng zuò.",
        phraseEs: "Por favor pasa, por favor siéntate.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "谢谢",
        image: "../images-chosen-chinese/谢谢.png",
        pinyin: "xièxie",
        meaning: "GRACIAS",
        type: "Verbo",
        level: "HSK 1",
        strokeCount: 24,
        radical: "讠 (Habla)",
        phraseCn: "谢谢你帮我。",
        phrasePinyin: "Xièxie nǐ bāng wǒ.",
        phraseEs: "Gracias por ayudarme.",
        colorTheme: "from-indigo-500 to-purple-600"
    },
    {
        character: "再见",
        image: "../images-chosen-chinese/再见.png",
        pinyin: "zàijiàn",
        meaning: "Despedirse",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "老师，再见！",
        phrasePinyin: "Lǎoshī, zàijiàn!",
        phraseEs: "¡Adiós, profesor!",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "对不起",
        image: "../images-chosen-chinese/对不起.png",
        pinyin: "duìbuqǐ",
        meaning: "Disculparse",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "对不起，我来晚了。",
        phrasePinyin: "Duìbuqǐ, wǒ lái wǎn le.",
        phraseEs: "Lo siento, he llegado tarde.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "没关系",
        image: "../images-chosen-chinese/对不起.png",
        pinyin: "méi guānxi",
        meaning: "Disculpar",
        type: "Verbo",
        level: "HSK 1",
        phraseCn: "对不起。- 没关系。",
        phrasePinyin: "Duìbuqǐ. - Méi guānxi.",
        phraseEs: "Lo siento. - No pasa nada.",
        colorTheme: "from-amber-500 to-orange-600"
    },
    {
        character: "家",
        image: "../images-chosen-chinese/家.png",
        pinyin: "jiā",
        meaning: "Casa",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我家在北京。",
        phrasePinyin: "Wǒ jiā zài Běijīng.",
        phraseEs: "Mi casa está en Pekín.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "爸爸",
        image: "../images-chosen-chinese/爸爸.png",
        pinyin: "bàba",
        meaning: "Papá",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我爸爸是医生。",
        phrasePinyin: "Wǒ bàba shì yīshēng.",
        phraseEs: "Mi papá es médico.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "妈妈",
        image: "../images-chosen-chinese/妈妈.png",
        pinyin: "māma",
        meaning: "Mamá",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我妈妈不工作。",
        phrasePinyin: "Wǒ māma bù gōngzuò.",
        phraseEs: "Mi mamá no trabaja.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "儿子",
        image: "../images-chosen-chinese/儿子.png",
        pinyin: "érzi",
        meaning: "Hijo",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "他儿子今年八岁。",
        phrasePinyin: "Tā érzi jīnnián bā suì.",
        phraseEs: "Su hijo tiene ochos años este año.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "女儿",
        image: "../images-chosen-chinese/女儿.png",
        pinyin: "nǚ'ér",
        meaning: "Hija",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我有一个女儿。",
        phrasePinyin: "Wǒ yǒu yī gè nǚ'ér.",
        phraseEs: "Tengo una hija.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "老师",
        image: "../images-chosen-chinese/老师.png",
        pinyin: "lǎoshī",
        meaning: "Profesor",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "王老师在教汉语。",
        phrasePinyin: "Wáng lǎoshī zài jiāo Hànyǔ.",
        phraseEs: "El profesor Wang está enseñando chino.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "学生",
        image: "../images-chosen-chinese/学生.png",
        pinyin: "xuésheng",
        meaning: "Estudiante",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我们学校的学生很多。",
        phrasePinyin: "Wǒmen xuéxiào de xuésheng hěn duō.",
        phraseEs: "Nuestra escuela tiene muchos estudiantes.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "同学",
        image: "../images-chosen-chinese/学生.png",
        pinyin: "tóngxué",
        meaning: "Compañero",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "她是我的大学同学。",
        phrasePinyin: "Tā shì wǒ de dàxué tóngxué.",
        phraseEs: "Ella es mi compañera de la universidad.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "朋友",
        image: "../images-chosen-chinese/朋友.png",
        pinyin: "péngyou",
        meaning: "Amigo",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "他是我的好朋友。",
        phrasePinyin: "Tā shì wǒ de hǎo péngyou.",
        phraseEs: "Él es mi buen amigo.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "医生",
        image: "../images-chosen-chinese/医生.png",
        pinyin: "yīshēng",
        meaning: "Médico",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "这个医生很好。",
        phrasePinyin: "Zhège yīshēng hěn hǎo.",
        phraseEs: "Este médico es muy bueno.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "先生",
        image: "../images-chosen-chinese/先生.png",
        pinyin: "xiānsheng",
        meaning: "Señor",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "张先生在办公室。",
        phrasePinyin: "Zhāng xiānsheng zài bàngōngshì.",
        phraseEs: "El señor Zhang está en la oficina.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "小姐",
        image: "../images-chosen-chinese/小姐.png",
        pinyin: "xiǎojiě",
        meaning: "Señorita",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "李小姐喜欢买衣服。",
        phrasePinyin: "Lǐ xiǎojiě xǐhuan mǎi yīfu.",
        phraseEs: "A la señorita Li le gusta comprar ropa.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "人",
        image: "../images-chosen-chinese/人.png",
        image: "../images-chosen-chinese/人.png",
        pinyin: "rén",
        meaning: "PERSONA",
        type: "Sustantivo",
        level: "HSK 1",
        strokeCount: 2,
        radical: "人 (Persona)",
        phraseCn: "商店里有很多人。",
        phrasePinyin: "Shāngdiàn lǐ yǒu hěn duō rén.",
        phraseEs: "Hay mucha gente en la tienda.",
        colorTheme: "from-violet-500 to-fuchsia-600"
    },
    {
        character: "学校",
        image: "../images-chosen-chinese/学校.png",
        pinyin: "xuéxiào",
        meaning: "Escuela",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我去学校看书。",
        phrasePinyin: "Wǒ qù xuéxiào kàn shū.",
        phraseEs: "Voy a la escuela a leer libros.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "饭馆",
        image: "../images-chosen-chinese/饭馆.png",
        pinyin: "fànguǎn",
        meaning: "Restaurante",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "这家饭馆的菜很好吃。",
        phrasePinyin: "Zhè jiā fànguǎn de cài hěn hǎochī.",
        phraseEs: "La comida de este restaurante está riquísima.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "商店",
        image: "../images-chosen-chinese/商店.png",
        pinyin: "shāngdiàn",
        meaning: "Tienda",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我去商店买杯子。",
        phrasePinyin: "Wǒ qù shāngdiàn mǎi bēizi.",
        phraseEs: "Voy a la tienda a comprar una taza.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "医院",
        image: "../images-chosen-chinese/医院.png",
        pinyin: "yīyuàn",
        meaning: "Hospital",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "他在医院里住。",
        phrasePinyin: "Tā zài yīyuàn lǐ zhù.",
        phraseEs: "Él está ingresado en el hospital.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "火车站",
        image: "../images-chosen-chinese/火车站.png",
        pinyin: "huǒchēzhàn",
        meaning: "Estación",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我在火车站等他。",
        phrasePinyin: "Wǒ zài huǒchēzhàn děng tā.",
        phraseEs: "Le estoy esperando en la estación de tren.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "中国",
        image: "../images-chosen-chinese/中国.png",
        pinyin: "Zhōngguó",
        meaning: "China",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我想去中国旅游。",
        phrasePinyin: "Wǒ xiǎng qù Zhōngguó lǚyóu.",
        phraseEs: "Quiero viajar a China.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "北京",
        image: "../images-chosen-chinese/北京.png",
        pinyin: "Běijīng",
        meaning: "Pekín",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "北京的天气很冷。",
        phrasePinyin: "Běijīng de tiānqì hěn lěng.",
        phraseEs: "El tiempo en Pekín es muy frío.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "上",
        image: "../images-chosen-chinese/上.png",
        image: "../images-chosen-chinese/上.png",
        pinyin: "shàng",
        meaning: "Encima",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "桌子上有电脑。",
        phrasePinyin: "Zhuōzi shàng yǒu diànnǎo.",
        phraseEs: "Hay un ordenador sobre la mesa.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "下",
        image: "../images-chosen-chinese/下.png",
        image: "../images-chosen-chinese/下.png",
        pinyin: "xià",
        meaning: "Debajo",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "椅子的下面有一只猫。",
        phrasePinyin: "Yǐzi de xiàmiàn yǒu yī zhī māo.",
        phraseEs: "Debajo de la silla hay un gato.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "前面",
        image: "../images-chosen-chinese/前面.png",
        pinyin: "qiánmiàn",
        meaning: "Delante",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "学校前面有一个商店。",
        phrasePinyin: "Xuéxiào qiánmiàn yǒu yī gè shāngdiàn.",
        phraseEs: "Delante de la escuela hay una tienda.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "后面",
        image: "../images-chosen-chinese/后面.png",
        pinyin: "hòumiàn",
        meaning: "Detrás",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我家后面有一个饭馆。",
        phrasePinyin: "Wǒ jiā hòumiàn yǒu yī gè fànguǎn.",
        phraseEs: "Detrás de mi casa hay un restaurante.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "里面",
        image: "../images-chosen-chinese/里面.png",
        pinyin: "lǐmiàn",
        meaning: "Dentro",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "杯子里面没有水。",
        phrasePinyin: "Bēizi lǐmiàn méiyǒu shuǐ.",
        phraseEs: "No hay agua dentro de la taza.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "年",
        image: "../images-chosen-chinese/年.png",
        image: "../images-chosen-chinese/年.png",
        pinyin: "nián",
        meaning: "Año",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我在中国住了一年。",
        phrasePinyin: "Wǒ zài Zhōngguó zhù le yī nián.",
        phraseEs: "Viví un año en China.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "月",
        image: "../images-chosen-chinese/月.png",
        image: "../images-chosen-chinese/月.png",
        pinyin: "yuè",
        meaning: "Mes",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "今年十二月天气很冷。",
        phrasePinyin: "Jīnnián shí'èr yuè tiānqì hěn lěng.",
        phraseEs: "Este diciembre hace mucho frío.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "日",
        image: "../images-chosen-chinese/日.png",
        image: "../images-chosen-chinese/日.png",
        pinyin: "rì",
        meaning: "Día",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "今天是五月十七日。",
        phrasePinyin: "Jīntiān shì wǔ yuè shíqī rì.",
        phraseEs: "Hoy es 17 de mayo.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "星期",
        image: "../images-chosen-chinese/星期.png",
        pinyin: "xīngqī",
        meaning: "Semana",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "一个星期有七天。",
        phrasePinyin: "Yī gè xīngqī yǒu qī tiān.",
        phraseEs: "Una semana tiene siete días.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "点",
        image: "../images-chosen-chinese/点.png",
        pinyin: "diǎn",
        meaning: "Hora",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "现在是上午九点。",
        phrasePinyin: "Xiànzài shì shàngwǔ jiǔ diǎn.",
        phraseEs: "Ahora son las nueve de la mañana.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "分钟",
        image: "../images-chosen-chinese/分钟.png",
        pinyin: "fēnzhōng",
        meaning: "Minuto",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "请等我十分钟。",
        phrasePinyin: "Qǐng děng wǒ shí fēnzhōng.",
        phraseEs: "Por favor, espérame diez minutos.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "现在",
        image: "../images-chosen-chinese/现在.png",
        pinyin: "xiànzài",
        meaning: "Ahora",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "现在是下午三点。",
        phrasePinyin: "Xiànzài shì xiàwǔ sān diǎn.",
        phraseEs: "Ahora son las tres de la tarde.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "时候",
        image: "../images-chosen-chinese/时候.png",
        pinyin: "shíhou",
        meaning: "Momento",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "你什么时候回家？",
        phrasePinyin: "Nǐ shénme shíhou huí jiā?",
        phraseEs: "语¿Cuándo vas a volver a casa?",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "今天",
        image: "../images-chosen-chinese/今天.png",
        pinyin: "jīntiān",
        meaning: "Hoy",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "今天的天气很好。",
        phrasePinyin: "Jīntiān de tiānqì hěn hǎo.",
        phraseEs: "El tiempo de hoy está muy bien.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "明天",
        image: "../images-chosen-chinese/明天.png",
        pinyin: "míngtiān",
        meaning: "Mañana",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "明天我们去买东西。",
        phrasePinyin: "Míngtiān wǒmen qù mǎi dōngxi.",
        phraseEs: "Mañana iremos de compras.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "昨天",
        image: "../images-chosen-chinese/昨天.png",
        pinyin: "zuótiān",
        meaning: "Ayer",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "昨天在下雨。",
        phrasePinyin: "Zuótiān zài xiàyǔ.",
        phraseEs: "Ayer estuvo lloviendo.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "上午",
        image: "../images-chosen-chinese/上午.png",
        pinyin: "shàngwǔ",
        meaning: "Por la mañana",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我上午十点去学校。",
        phrasePinyin: "Wǒ shàngwǔ shí diǎn qù xuéxiào.",
        phraseEs: "Voy a la escuela a las diez de la mañana.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "中午",
        image: "../images-chosen-chinese/中午.png",
        pinyin: "zhōngwǔ",
        meaning: "Mediodía",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "中午我们在饭馆吃饭。",
        phrasePinyin: "Zhōngwǔ wǒmen zài fànguǎn chī fàn.",
        phraseEs: "Al mediodía comemos en el restaurante.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "下午",
        image: "../images-chosen-chinese/下午.png",
        pinyin: "xiàwǔ",
        meaning: "Tarde",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我下午四点看电影。",
        phrasePinyin: "Wǒ xiàwǔ sì diǎn kàn diànyǐng.",
        phraseEs: "Veo una película a las cuatro de la tarde.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "桌子",
        image: "../images-chosen-chinese/桌子.png",
        pinyin: "zhuōzi",
        meaning: "Mesa",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "桌子上有一本书。",
        phrasePinyin: "Zhuōzi shàng yǒu yī běn shū.",
        phraseEs: "Hay un libro sobre la mesa.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "椅子",
        image: "../images-chosen-chinese/椅子.png",
        pinyin: "yǐzi",
        meaning: "Silla",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "请坐在这把椅子上。",
        phrasePinyin: "Qǐng zuò zài zhè bǎ yǐzi shàng.",
        phraseEs: "Por favor, siéntate en esta silla.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "杯子",
        image: "../images-chosen-chinese/杯子.png",
        pinyin: "bēizi",
        meaning: "Vaso / Taza",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "这个杯子是谁的？",
        phrasePinyin: "Zhège bēizi ...",
        phraseEs: "¿De quién es esta taza?",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "茶",
        image: "../images-chosen-chinese/茶.png",
        pinyin: "chá",
        meaning: "Té",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "请喝热茶。",
        phrasePinyin: "Qǐng hē rè chá.",
        phraseEs: "Por favor, bebe té caliente.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "水",
        image: "../images-chosen-chinese/水.png",
        image: "../images-chosen-chinese/水.png",
        pinyin: "shuǐ",
        meaning: "AGUA",
        type: "Sustantivo",
        level: "HSK 1",
        strokeCount: 4,
        radical: "水 (Agua)",
        phraseCn: "我想喝点儿水。",
        phrasePinyin: "Wǒ xiǎng hē diǎnr shuǐ.",
        phraseEs: "Quiero beber un poco de agua.",
        colorTheme: "from-sky-500 to-indigo-600"
    },
    {
        character: "菜",
        image: "../images-chosen-chinese/菜.png",
        pinyin: "cài",
        meaning: "Plato",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "妈妈做的菜很好吃。",
        phrasePinyin: "Māma zuò de cài hěn hǎochī.",
        phraseEs: "Los platos que hace mamá están muy ricos.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "米饭",
        image: "../images-chosen-chinese/米饭.png",
        pinyin: "mǐfàn",
        meaning: "Arroz",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我喜欢吃米饭。",
        phrasePinyin: "Wǒ xǐhuan chī mǐfàn.",
        phraseEs: "Me gusta comer arroz.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "苹果",
        image: "../images-chosen-chinese/苹果.png",
        pinyin: "píngguǒ",
        meaning: "Manzana",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我买了一些苹果。",
        phrasePinyin: "Wǒ mǎi le yīxiē píngguǒ.",
        phraseEs: "He comprado algunas manzanas.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "衣服",
        image: "../images-chosen-chinese/衣服.png",
        pinyin: "yīfu",
        meaning: "Ropa",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "这里的衣服很漂亮。",
        phrasePinyin: "Zhèlǐ de yīfu hěn piàoliang.",
        phraseEs: "La ropa de aquí es muy bonita.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "钱",
        image: "../images-chosen-chinese/钱.png",
        pinyin: "qián",
        meaning: "Dinero",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我没有很多钱。",
        phrasePinyin: "Wǒ méiyǒu hěn duō qián.",
        phraseEs: "No tengo mucho dinero.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "书",
        image: "../images-chosen-chinese/书.png",
        pinyin: "shū",
        meaning: "Libro",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我看了一本好书。",
        phrasePinyin: "Wǒ kàn le yī běn hǎo shū.",
        phraseEs: "He leído un buen libro.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "汉语",
        image: "../images-chosen-chinese/汉语.png",
        pinyin: "Hànyǔ",
        meaning: "Chino",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我们的老师教汉语。",
        phrasePinyin: "Wǒmen de lǎoshī jiāo Hànyǔ.",
        phraseEs: "Nuestro profesor enseña chino.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "字",
        image: "../images-chosen-chinese/字.png",
        image: "../images-chosen-chinese/字.png",
        pinyin: "zì",
        meaning: "Carácter",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "这个汉字怎么写？",
        phrasePinyin: "Zhège Hànzì zěnme xiě?",
        phraseEs: "¿Cómo se escribe este carácter chino?",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "名字",
        image: "../images-chosen-chinese/名字.png",
        pinyin: "míngzi",
        meaning: "Nombre",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "你的名字叫什么？",
        phrasePinyin: "Nǐ de míngzi jiào shénme?",
        phraseEs: "¿Cómo te llamas?",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "电脑",
        image: "../images-chosen-chinese/电脑.png",
        pinyin: "diànnǎo",
        meaning: "Ordenador",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "这是我的新电脑。",
        phrasePinyin: "Zhè iOS hī wǒ de xīn diànnǎo.",
        phraseEs: "Este es mi nuevo ordenador.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "电视",
        image: "../images-chosen-chinese/电视.png",
        pinyin: "diànshì",
        meaning: "Televisión",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "孩子们在看电视。",
        phrasePinyin: "Háizimen zài kàn diànshì.",
        phraseEs: "Los niños están viendo la televisión.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "电影",
        image: "../images-chosen-chinese/电影.png",
        pinyin: "diànyǐng",
        meaning: "Película",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "星期六我们去看电影。",
        phrasePinyin: "Xīngqīliù wǒmen qù kàn diànyǐng.",
        phraseEs: "El sábado vamos a ir a ver una película.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "飞机",
        image: "../images-chosen-chinese/飞机.png",
        pinyin: "fēijī",
        meaning: "Avión",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我明天坐飞机去北京。",
        phrasePinyin: "Wǒ míngtiān zuò fēijī qù Běijīng.",
        phraseEs: "Mañana voy en avión a Pekín.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "出租车",
        image: "../images-chosen-chinese/出租车.png",
        pinyin: "chūzūchē",
        meaning: "Taxi",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我们坐出租车去火车站。",
        phrasePinyin: "Wǒmen zuò chūzūchē qù huǒchēzhàn.",
        phraseEs: "Vamos en taxi a la estación de tren.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "猫",
        image: "../images-chosen-chinese/猫.png",
        pinyin: "māo",
        meaning: "GATO",
        type: "Sustantivo",
        level: "HSK 1",
        strokeCount: 11,
        radical: "犭 (Perro/Animal)",
        phraseCn: "那只猫在桌子下面。",
        phrasePinyin: "Nà zhī māo zài zhuōzi xiàmiàn.",
        phraseEs: "Aquel gato está debajo de la mesa.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "狗",
        image: "../images-chosen-chinese/狗.png",
        pinyin: "gǒu",
        meaning: "Perro",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "我家有一只小狗。",
        phrasePinyin: "Wǒ jiā yǒu yī zhī xiǎo gǒu.",
        phraseEs: "En mi casa hay un perro pequeño.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "东西",
        image: "../images-chosen-chinese/东西.png",
        pinyin: "dōngxi",
        meaning: "Cosa",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "你在商店买了什么东西？",
        phrasePinyin: "Nǐ zài shāngdiàn mǎi le shénme dōngxi?",
        phraseEs: "¿Qué cosas has comprado en la tienda?",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "天气",
        image: "../images-chosen-chinese/天气.png",
        pinyin: "tiānqì",
        meaning: "Clima",
        type: "Sustantivo",
        level: "HSK 1",
        phraseCn: "今天的天气怎么样？",
        phrasePinyin: "Jīntiān de tiānqì zěnmeyàng?",
        phraseEs: "¿Qué tal está el tiempo hoy?",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "个",
        image: "../images-chosen-chinese/个.png",
        pinyin: "gè",
        meaning: "Unidad (general)",
        type: "Clasificador",
        level: "HSK 1",
        phraseCn: "我有一个哥哥。",
        phrasePinyin: "Wǒ yǒu yī gè gēge.",
        phraseEs: "Tengo un hermano mayor.",
        colorTheme: "from-cyan-500 to-blue-600"
    },
    {
        character: "岁",
        image: "../images-chosen-chinese/岁.png",
        pinyin: "suì",
        meaning: "Años",
        type: "Clasificador",
        level: "HSK 1",
        phraseCn: "我儿子今年六岁。",
        phrasePinyin: "Wǒ érzi jīnnián liù suì.",
        phraseEs: "Mi hijo tiene seis años este año.",
        colorTheme: "from-cyan-500 to-blue-600"
    },
    {
        character: "本",
        image: "../images-chosen-chinese/本.png",
        image: "../images-chosen-chinese/本.png",
        pinyin: "běn",
        meaning: "Tomo (libros)",
        type: "Clasificador",
        level: "HSK 1",
        phraseCn: "桌子上有一本书。",
        phrasePinyin: "Zhuōzi shàng yǒu yī běn shū.",
        phraseEs: "Hay un libro sobre la mesa.",
        colorTheme: "from-cyan-500 to-blue-600"
    },
    {
        character: "些",
        image: "../images-chosen-chinese/些.png",
        pinyin: "xiē",
        meaning: "Algunos",
        type: "Clasificador",
        level: "HSK 1",
        phraseCn: "these苹果很好吃。",
        phrasePinyin: "Zhèxiē píngguǒ hěn hǎochī.",
        phraseEs: "Estas manzanas están muy ricas.",
        colorTheme: "from-cyan-500 to-blue-600"
    },
    {
        character: "块",
        image: "../images-chosen-chinese/块.png",
        pinyin: "kuài",
        meaning: "Pedazo",
        type: "Clasificador",
        level: "HSK 1",
        phraseCn: "这一块肉很好。",
        phrasePinyin: "Zhè yī kuài ròu hěn hǎo.",
        phraseEs: "Este trozo de carne está muy bueno.",
        colorTheme: "from-cyan-500 to-blue-600"
    },
    {
        character: "一",
        image: "../images-chosen-chinese/一.png",
        image: "../images-chosen-chinese/一.png",
        pinyin: "yī",
        meaning: "Uno",
        type: "Número",
        level: "HSK 1",
        phraseCn: "我有一只猫。",
        phrasePinyin: "Wǒ yǒu yī zhī māo.",
        phraseEs: "Tengo un gato.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "二",
        image: "../images-chosen-chinese/二.png",
        image: "../images-chosen-chinese/二.png",
        pinyin: "èr",
        meaning: "Dos",
        type: "Número",
        level: "HSK 1",
        phraseCn: "我买二斤苹果。",
        phrasePinyin: "Wǒ mǎi èr jīn píngguǒ.",
        phraseEs: "Compro dos jins de manzanas.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "三",
        image: "../images-chosen-chinese/三.png",
        image: "../images-chosen-chinese/三.png",
        pinyin: "sān",
        meaning: "Tres",
        type: "Número",
        level: "HSK 1",
        phraseCn: "房间里有三个人。",
        phrasePinyin: "Fángjiān lǐ yǒu sān gè rén.",
        phraseEs: "Hay tres personas en la habitación.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "四",
        image: "../images-chosen-chinese/四.png",
        image: "../images-chosen-chinese/四.png",
        pinyin: "sì",
        meaning: "Cuatro",
        type: "Número",
        level: "HSK 1",
        phraseCn: "这个苹果四块钱。",
        phrasePinyin: "Zhège píngguǒ sì kuài qián.",
        phraseEs: "Esta manzana cuesta cuatro yuanes.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "五",
        image: "../images-chosen-chinese/五.png",
        pinyin: "wǔ",
        meaning: "Cinco",
        type: "Número",
        level: "HSK 1",
        phraseCn: "我在北京住五天。",
        phrasePinyin: "Wǒ zài Běijīng zhù wǔ tiān.",
        phraseEs: "Me quedo en Pekín cinco días.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "六",
        image: "../images-chosen-chinese/六.png",
        image: "../images-chosen-chinese/六.png",
        pinyin: "liù",
        meaning: "Seis",
        type: "Número",
        level: "HSK 1",
        phraseCn: "现在是六点二十。",
        phrasePinyin: "Xiànzài ...",
        phraseEs: "Ahora son las seis y veinte.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "七",
        image: "../images-chosen-chinese/七.png",
        image: "../images-chosen-chinese/七.png",
        pinyin: "qī",
        meaning: "Siete",
        type: "Número",
        level: "HSK 1",
        phraseCn: "一个星期有七天。",
        phrasePinyin: "Yī gè xīngqī yǒu qī tiān.",
        phraseEs: "Una semana tiene siete días.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "八",
        image: "../images-chosen-chinese/八.png",
        image: "../images-chosen-chinese/八.png",
        pinyin: "bā",
        meaning: "Ocho",
        type: "Número",
        level: "HSK 1",
        phraseCn: "他女儿今年八岁。",
        phrasePinyin: "Tā nǚ'ér jīnnián bā suì.",
        phraseEs: "Su hija tiene ocho años este año.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "九",
        image: "../images-chosen-chinese/九.png",
        image: "../images-chosen-chinese/九.png",
        pinyin: "jiǔ",
        meaning: "Nueve",
        type: "Número",
        level: "HSK 1",
        phraseCn: "学校里有九个老师。",
        phrasePinyin: "Xuéxiào lǐ yǒu jiǔ gè lǎoshī.",
        phraseEs: "Hay nueve profesores en la escuela.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "十",
        image: "../images-chosen-chinese/十.png",
        image: "../images-chosen-chinese/十.png",
        pinyin: "shí",
        meaning: "Diez",
        type: "Número",
        level: "HSK 1",
        phraseCn: "这里有十个杯子。",
        phrasePinyin: "Zhèlǐ ...",
        phraseEs: "Aquí hay diez tazas.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "零",
        image: "../images-chosen-chinese/零.png",
        pinyin: "líng",
        meaning: "Cero",
        type: "Número",
        level: "HSK 1",
        phraseCn: "今年是二零二六年。",
        phrasePinyin: "Jīnnián ...",
        phraseEs: "Este año es 2026.",
        colorTheme: "from-teal-500 to-green-600"
    },
    {
        character: "不",
        image: "../images-chosen-chinese/不.png",
        pinyin: "bù",
        meaning: "No",
        type: "Adverbio",
        level: "HSK 1",
        phraseCn: "我不认识那个人。",
        phrasePinyin: "Wǒ bù rènshi nàge rén.",
        phraseEs: "No conozco a esa persona.",
        colorTheme: "from-violet-500 to-fuchsia-600"
    },
    {
        character: "没",
        image: "../images-chosen-chinese/没.png",
        pinyin: "méi",
        meaning: "No",
        type: "Adverbio",
        level: "HSK 1",
        phraseCn: "我没有钱。",
        phrasePinyin: "Wǒ méiyǒu qián.",
        phraseEs: "No tengo dinero.",
        colorTheme: "from-violet-500 to-fuchsia-600"
    },
    {
        character: "很",
        image: "../images-chosen-chinese/很.png",
        pinyin: "hěn",
        meaning: "Muy",
        type: "Adverbio",
        level: "HSK 1",
        phraseCn: "今天的空气很好。",
        phrasePinyin: "Jīntiān de kōngqì hěn hǎo.",
        phraseEs: "El aire de hoy está muy bueno.",
        colorTheme: "from-violet-500 to-fuchsia-600"
    },
    {
        character: "太",
        image: "../images-chosen-chinese/太.png",
        pinyin: "tài",
        meaning: "Demasiado",
        type: "Adverbio",
        level: "HSK 1",
        phraseCn: "这个天气太热了。",
        phrasePinyin: "Zhège tiānqì tài rè le.",
        phraseEs: "Hace demasiado calor en este clima.",
        colorTheme: "from-violet-500 to-fuchsia-600"
    },
    {
        character: "都",
        image: "../images-chosen-chinese/都.png",
        pinyin: "dōu",
        meaning: "Todos",
        type: "Adverbio",
        level: "HSK 1",
        phraseCn: "我们都是学生。",
        phrasePinyin: "Wǒmen dōu ...",
        phraseEs: "Todos nosotros somos estudiantes.",
        colorTheme: "from-violet-500 to-fuchsia-600"
    },
    {
        character: "和",
        image: "../images-chosen-chinese/和.png",
        pinyin: "hé",
        meaning: "Y",
        type: "Conjunción",
        level: "HSK 1",
        phraseCn: "我和他是好朋友。",
        phrasePinyin: "Wǒ hé tā ...",
        phraseEs: "Él y yo somos buenos amigos.",
        colorTheme: "from-gray-500 to-slate-600"
    },
    {
        character: "在",
        image: "../images-chosen-chinese/在.png",
        pinyin: "zài",
        meaning: "En",
        type: "Preposición",
        level: "HSK 1",
        phraseCn: "爸爸在家里睡觉。",
        phrasePinyin: "Bàba zài ...",
        phraseEs: "Papá está durmiendo en casa.",
        colorTheme: "from-gray-500 to-slate-600"
    },
    {
        character: "吗",
        image: "../images-chosen-chinese/吗.png",
        pinyin: "ma",
        meaning: "Interrogativa",
        type: "Partícula",
        level: "HSK 1",
        phraseCn: "你喜欢中国菜吗？",
        phrasePinyin: "Nǐ xǐhuan ...",
        phraseEs: "¿Te gusta la comida china?",
        colorTheme: "from-gray-500 to-slate-600"
    },
    {
        character: "呢",
        image: "../images-chosen-chinese/呢.png",
        pinyin: "ne",
        meaning: "Sujetiva",
        type: "Partícula",
        level: "HSK 1",
        phraseCn: "我很好，你呢？",
        phrasePinyin: "Wǒ hěn hǎo, nǐ ne?",
        phraseEs: "Estoy muy bien, ¿y tú?",
        colorTheme: "from-gray-500 to-slate-600"
    },
    {
        character: "了",
        image: "../images-chosen-chinese/了.png",
        pinyin: "le",
        meaning: "Pasado",
        type: "Partícula",
        level: "HSK 1",
        phraseCn: "我看见他了。",
        phrasePinyin: "Wǒ kànjiàn tā le.",
        phraseEs: "Ya lo he visto.",
        colorTheme: "from-gray-500 to-slate-600"
    },
    {
        character: "的",
        image: "../images-chosen-chinese/的.png",
        pinyin: "de",
        meaning: "De",
        type: "Partícula",
        level: "HSK 1",
        phraseCn: "这是我的电脑。",
        phrasePinyin: "Zhè shì wǒ de diànnǎo.",
        phraseEs: "Este es mi ordenador.",
        colorTheme: "from-gray-500 to-slate-600"
    },
    {
        character: "大",
        image: "../images-chosen-chinese/大.png",
        image: "../images-chosen-chinese/大.png",
        pinyin: "dà",
        meaning: "GRANDE",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 3,
        radical: "大 (Grande)",
        phraseCn: "这个苹果很大。",
        phrasePinyin: "Zhège píngguǒ hěn dà.",
        phraseEs: "Esta manzana es muy grande.",
        colorTheme: "from-emerald-500 to-teal-600"
    },
    {
        character: "小",
        image: "../images-chosen-chinese/小.png",
        image: "../images-chosen-chinese/小.png",
        pinyin: "xiǎo",
        meaning: "Pequeño",
        type: "Adjetivo",
        level: "HSK 1",
        phraseCn: "那只猫很小。",
        phrasePinyin: "Nà zhī māo hěn xiǎo.",
        phraseEs: "Aquel gato es muy pequeño.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "多",
        image: "../images-chosen-chinese/多.png",
        pinyin: "duō",
        meaning: "Mucho",
        type: "Adjetivo",
        level: "HSK 1",
        phraseCn: "学校里有很多人。",
        phrasePinyin: "Xuéxiào lǐ yǒu hěn duō rén.",
        phraseEs: "Hay mucha gente en la escuela.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "少",
        image: "../images-chosen-chinese/少.png",
        pinyin: "shǎo",
        meaning: "Poco",
        type: "Adjetivo",
        level: "HSK 1",
        phraseCn: "杯子里的水很少。",
        phrasePinyin: "Bēizi lǐ de shuǐ hěn shǎo.",
        phraseEs: "Hay muy poca agua en la taza.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "好",
        image: "../images-chosen-chinese/好.png",
        pinyin: "hǎo",
        meaning: "BUENO / BIEN",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 6,
        radical: "女 (Mujer) + 子 (Hijo)",
        phraseCn: "今天是一个好天气。",
        phrasePinyin: "Jīntiān ...",
        phraseEs: "Hoy hace un buen día.",
        colorTheme: "from-cyan-500 to-blue-600"
    },
    {
        character: "冷",
        image: "../images-chosen-chinese/冷.png",
        pinyin: "lěng",
        meaning: "Frío",
        type: "Adjetivo",
        level: "HSK 1",
        phraseCn: "昨天太冷了。",
        phrasePinyin: "Zuótiān tài lěng le.",
        phraseEs: "Ayer hizo demasiado frío.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "热",
        image: "../images-chosen-chinese/热.png",
        pinyin: "rè",
        meaning: "Caliente",
        type: "Adjetivo",
        level: "HSK 1",
        phraseCn: "房间里很热。",
        phrasePinyin: "Fángjiān lǐ hěn rè.",
        phraseEs: "Hace mucho calor en la habitación.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "高兴",
        image: "../images-chosen-chinese/高兴.png",
        pinyin: "gāoxìng",
        meaning: "Contento",
        type: "Adjetivo",
        level: "HSK 1",
        phraseCn: "认识你很高兴。",
        phrasePinyin: "Rènshi nǐ hěn gāoxìng.",
        phraseEs: "Encantado de conocerte.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "漂亮",
        image: "../images-chosen-chinese/漂亮.png",
        pinyin: "piàoliang",
        meaning: "Bonito",
        type: "Adjetivo",
        level: "HSK 1",
        phraseCn: "她的衣服很漂亮。",
        phrasePinyin: "Tā de yīfu hěn piàoliang.",
        phraseEs: "Su ropa es muy bonita.",
        colorTheme: "from-pink-500 to-rose-600"
    },
    {
        character: "白色",
        pinyin: "báisè",
        meaning: "Blanco",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 5,
        radical: "白 (Blanco)",
        phraseCn: "这只猫是白色的。",
        phrasePinyin: "Zhè zhī māo shì báisè de.",
        phraseEs: "Este gato es blanco.",
        colorTheme: "from-slate-100 to-zinc-300",
        colorHex: "#FFFFFF"
    },
    {
        character: "红色",
        pinyin: "hóngsè",
        meaning: "Rojo",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 6,
        radical: "纟 (Seda)",
        phraseCn: "他有一辆红色的自行车。",
        phrasePinyin: "Tā yǒu yí liàng hóngsè de zìxíngchē.",
        phraseEs: "Él tiene una bicicleta roja.",
        colorTheme: "from-red-500 to-rose-600",
        colorHex: "#EF4444"
    },
    {
        character: "蓝色",
        pinyin: "lánsè",
        meaning: "Azul",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 13,
        radical: "艹 (Hierba)",
        phraseCn: "天空是蓝色的。",
        phrasePinyin: "Tiānkōng shì lánsè de.",
        phraseEs: "El cielo es azul.",
        colorTheme: "from-blue-500 to-indigo-600",
        colorHex: "#3B82F6"
    },
    {
        character: "绿色",
        pinyin: "lǜsè",
        meaning: "Verde",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 11,
        radical: "纟 (Seda)",
        phraseCn: "桌子上有一个绿色的苹果。",
        phrasePinyin: "Zhuōzi shàng yǒu yí ge lǜsè de píngguǒ.",
        phraseEs: "Hay una manzana verde sobre la mesa.",
        colorTheme: "from-emerald-500 to-teal-600",
        colorHex: "#10B981"
    },
    {
        character: "黄色",
        pinyin: "huángsè",
        meaning: "Amarillo",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 11,
        radical: "黄 (Amarillo)",
        phraseCn: "这是一杯黄色的茶。",
        phrasePinyin: "Zhè shì yì bēi huángsè de chá.",
        phraseEs: "Esta es una taza de té amarillo.",
        colorTheme: "from-yellow-400 to-amber-500",
        colorHex: "#FBBF24"
    },
    {
        character: "黑色",
        pinyin: "hēisè",
        meaning: "Negro",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 12,
        radical: "黑 (Negro)",
        phraseCn: "妹妹买了一双黑色的鞋子。",
        phrasePinyin: "Mèimei mǎi le yì shuāng hēisè de xiézi.",
        phraseEs: "Mi hermana menor compró un par de zapatos negros.",
        colorTheme: "from-slate-800 to-slate-950",
        colorHex: "#1E293B"
    },
    {
        character: "橙色",
        pinyin: "chéngsè",
        meaning: "Naranja",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 16,
        radical: "木 (Madera)",
        phraseCn: "他喜欢穿橙色的衣服。",
        phrasePinyin: "Tā xǐhuan chuān chéngsè de yīfu.",
        phraseEs: "A él le gusta vestir ropa naranja.",
        colorTheme: "from-orange-400 to-red-500",
        colorHex: "#F97316"
    },
    {
        character: "紫色",
        pinyin: "zǐsè",
        meaning: "Morado",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 12,
        radical: "糸 (Seda)",
        phraseCn: "杯子里有紫色的葡萄。",
        phrasePinyin: "Bēizi lǐ yǒu zǐsè de pútao.",
        phraseEs: "Hay uvas moradas en el vaso.",
        colorTheme: "from-purple-500 to-indigo-600",
        colorHex: "#8B5CF6"
    },
    {
        character: "粉红色",
        pinyin: "fěnhóngsè",
        meaning: "Rosa",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 10,
        radical: "米 (Arroz)",
        phraseCn: "这朵花 is 粉红色的。", // Wait, let's write it in Chinese: "这朵花是粉红色的。"
        phraseCn: "这朵花是粉红色的。",
        phrasePinyin: "Zhè duǒ huā shì fěnhóngsè de.",
        phraseEs: "Esta flor es rosa.",
        colorTheme: "from-pink-400 to-rose-500",
        colorHex: "#EC4899"
    },
    {
        character: "灰色",
        pinyin: "huīsè",
        meaning: "Gris",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 6,
        radical: "火 (Fuego)",
        phraseCn: "今天的天气是灰色的。",
        phrasePinyin: "Jīntiān de tiānqì shì huīsè de.",
        phraseEs: "El día de hoy está gris.",
        colorTheme: "from-gray-400 to-gray-600",
        colorHex: "#6B7280"
    },
    {
        character: "金色",
        pinyin: "jīnsè",
        meaning: "Dorado",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 8,
        radical: "金 (Oro/Metal)",
        phraseCn: "她戴着一个金色的戒指。",
        phrasePinyin: "Tā dài zhe yí ge jīnsè de jièzhi.",
        phraseEs: "Ella lleva puesto un anillo dorado.",
        colorTheme: "from-amber-400 to-yellow-600",
        colorHex: "#F59E0B"
    },
    {
        character: "银色",
        pinyin: "yínsè",
        meaning: "Plateado",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 11,
        radical: "银 (Metal)", // wait, we mapped it as 银 (Metal) or 钅 (Metal)? Let's use 钅 (Metal) as simplified radical
        radical: "钅 (Metal)",
        phraseCn: "桌子上有一支银色的笔。",
        phrasePinyin: "Zhuōzi shàng yǒu yì zhī yínsè de bǐ.",
        phraseEs: "Hay un bolígrafo plateado en la mesa.",
        colorTheme: "from-slate-300 to-zinc-400",
        colorHex: "#94A3B8"
    },
    {
        character: "棕色",
        pinyin: "zōngsè",
        meaning: "Marrón",
        type: "Adjetivo",
        level: "HSK 1",
        strokeCount: 12,
        radical: "木 (Madera)",
        phraseCn: "这只熊是棕色的。",
        phrasePinyin: "Zhè zhī xióng shì zōngsè de.",
        phraseEs: "Este oso es marrón.",
        colorTheme: "from-amber-800 to-stone-900",
        colorHex: "#78350F"
    }
];
