const cardsData = [
    {
        "kanji": "一",
        "anki_furigana": "一[いち]",
        "level": "N5",
        "meaning": "Uno",
        "romaji": "ICHI",
        "type": "nom.",
        "phraseJp": "一から始めましょう。",
        "phraseRomaji": "Ichi kara hajimemashou.",
        "phraseEs": "Empecemos desde uno.",
        "image": "../images-chosen/一.png"
    },
    {
        "kanji": "右",
        "anki_furigana": "右[みぎ]",
        "level": "N5",
        "meaning": "Derecha",
        "romaji": "MIGI",
        "type": "nom.",
        "phraseJp": "右に曲がってください。",
        "phraseRomaji": "Migi ni magatte kudasai.",
        "phraseEs": "Gire a la derecha.",
        "image": "../images-chosen/右.png"
    },
    {
        "kanji": "雨",
        "anki_furigana": "雨[あめ]",
        "level": "N5",
        "meaning": "Lluvia",
        "romaji": "AME",
        "type": "nom.",
        "phraseJp": "雨が降っています。",
        "phraseRomaji": "Ame ga futte imasu.",
        "phraseEs": "Está lloviendo.",
        "image": "../images-chosen/雨.png"
    },
    {
        "kanji": "円",
        "anki_furigana": "円[えん]",
        "level": "N5",
        "meaning": "Yen",
        "romaji": "EN",
        "type": "nom.",
        "phraseJp": "千円あります。",
        "phraseRomaji": "Sen en arimasu.",
        "phraseEs": "Tengo mil yenes.",
        "image": "../images-chosen/円.png"
    },
    {
        "kanji": "王",
        "anki_furigana": "王[おう]",
        "level": "N5",
        "meaning": "Rey",
        "romaji": "OU",
        "type": "nom.",
        "phraseJp": "王様は城にいます。",
        "phraseRomaji": "Ousama wa shiro ni imasu.",
        "phraseEs": "El rey está en el castillo.",
        "image": "../images-chosen/王.png"
    },
    {
        "kanji": "音",
        "anki_furigana": "音[おと]",
        "level": "N5",
        "meaning": "Sonido",
        "romaji": "OTO",
        "type": "nom.",
        "phraseJp": "いい音ですね。",
        "phraseRomaji": "Ii oto desu ne.",
        "phraseEs": "Es un buen sonido.",
        "image": "../images-chosen/音.png"
    },
    {
        "kanji": "下",
        "anki_furigana": "下[くだ]る",
        "level": "N5",
        "meaning": "Abajo",
        "romaji": "SHITA",
        "type": "ver.",
        "phraseJp": "下に降りてください。",
        "phraseRomaji": "Shita ni orite kudasai.",
        "phraseEs": "Baje por favor.",
        "image": "../images-chosen/下.png"
    },
    {
        "kanji": "火",
        "anki_furigana": "火[ひ]",
        "level": "N5",
        "meaning": "Fuego",
        "romaji": "HI",
        "type": "nom.",
        "phraseJp": "火を消してください。",
        "phraseRomaji": "Hi o keshite kudasai.",
        "phraseEs": "Apague el fuego.",
        "image": "../images-chosen/火.png"
    },
    {
        "kanji": "花",
        "anki_furigana": "花[はな]",
        "level": "N5",
        "meaning": "Flor",
        "romaji": "HANA",
        "type": "nom.",
        "phraseJp": "花が咲きました。",
        "phraseRomaji": "Hana ga sakimashita.",
        "phraseEs": "La flor floreció.",
        "image": "../images-chosen/花.png"
    },
    {
        "kanji": "貝",
        "anki_furigana": "貝[かい]",
        "level": "N5",
        "meaning": "Marisco",
        "romaji": "KAI",
        "type": "nom.",
        "phraseJp": "貝を食べます。",
        "phraseRomaji": "Kai o tabemasu.",
        "phraseEs": "Como mariscos.",
        "image": "../images-chosen/貝.png"
    },
    {
        "kanji": "学",
        "anki_furigana": "学[まな]ぶ",
        "level": "N5",
        "meaning": "Estudio",
        "romaji": "GAKU",
        "type": "ver.",
        "phraseJp": "日本語を学びます。",
        "phraseRomaji": "Nihongo o manabimasu.",
        "phraseEs": "Estudio japonés.",
        "image": "../images-chosen/学.png"
    },
    {
        "kanji": "気",
        "anki_furigana": "気[き]",
        "level": "N5",
        "meaning": "Espíritu",
        "romaji": "KI",
        "type": "nom.",
        "phraseJp": "お元気ですか？",
        "phraseRomaji": "Ogenki desu ka?",
        "phraseEs": "¿Cómo estás?",
        "image": "../images-chosen/気.png"
    },
    {
        "kanji": "九",
        "anki_furigana": "九[きゅう]",
        "level": "N5",
        "meaning": "Nueve",
        "romaji": "KYUU",
        "type": "nom.",
        "phraseJp": "九時です。",
        "phraseRomaji": "Kyuuji desu.",
        "phraseEs": "Son las nueve.",
        "image": "../images-chosen/九.png"
    },
    {
        "kanji": "休",
        "anki_furigana": "休[やす]む",
        "level": "N5",
        "meaning": "Descanso",
        "romaji": "YASUMU",
        "type": "ver.",
        "phraseJp": "ちょっと休みましょう。",
        "phraseRomaji": "Chotto yasumimashou.",
        "phraseEs": "Descansemos un poco.",
        "image": "../images-chosen/休.png"
    },
    {
        "kanji": "玉",
        "anki_furigana": "玉[たま]",
        "level": "N5",
        "meaning": "Joya/Bola",
        "romaji": "TAMA",
        "type": "nom.",
        "phraseJp": "玉ねぎを買います。",
        "phraseRomaji": "Tamanegi o kaimasu.",
        "phraseEs": "Compro cebollas.",
        "image": "../images-chosen/玉.png"
    },
    {
        "kanji": "金",
        "anki_furigana": "金[かね]",
        "level": "N5",
        "meaning": "Dinero",
        "romaji": "KANE",
        "type": "nom.",
        "phraseJp": "お金がありません。",
        "phraseRomaji": "Okane ga arimasen.",
        "phraseEs": "No tengo dinero.",
        "image": "../images-chosen/金.png"
    },
    {
        "kanji": "空",
        "anki_furigana": "空[そら]",
        "level": "N5",
        "meaning": "Cielo",
        "romaji": "SORA",
        "type": "nom.",
        "phraseJp": "空が青いです。",
        "phraseRomaji": "Sora ga aoi desu.",
        "phraseEs": "El cielo está azul.",
        "image": "../images-chosen/空.png"
    },
    {
        "kanji": "月",
        "anki_furigana": "月[つき]",
        "level": "N5",
        "meaning": "Luna",
        "romaji": "TSUKI",
        "type": "nom.",
        "phraseJp": "月が綺麗ですね。",
        "phraseRomaji": "Tsuki ga kirei desu ne.",
        "phraseEs": "La luna está bonita.",
        "image": "../images-chosen/月.png"
    },
    {
        "kanji": "犬",
        "anki_furigana": "犬[いぬ]",
        "level": "N5",
        "meaning": "Perro",
        "romaji": "INU",
        "type": "nom.",
        "phraseJp": "犬を飼っています。",
        "phraseRomaji": "Inu o katte imasu.",
        "phraseEs": "Tengo un perro.",
        "image": "../images-chosen/犬.png"
    },
    {
        "kanji": "見",
        "anki_furigana": "見[み]る",
        "level": "N5",
        "meaning": "Ver",
        "romaji": "MIRU",
        "type": "ver.",
        "phraseJp": "テレビを見ます。",
        "phraseRomaji": "Terebi o mimasu.",
        "phraseEs": "Veo la televisión.",
        "image": "../images-chosen/見.png"
    },
    {
        "kanji": "五",
        "anki_furigana": "五[ご]",
        "level": "N5",
        "meaning": "Cinco",
        "romaji": "GO",
        "type": "nom.",
        "phraseJp": "五人います。",
        "phraseRomaji": "Gonin imasu.",
        "phraseEs": "Hay cinco personas.",
        "image": "../images-chosen/五.png"
    },
    {
        "kanji": "口",
        "anki_furigana": "口[くち]",
        "level": "N5",
        "meaning": "Boca",
        "romaji": "KUCHI",
        "type": "nom.",
        "phraseJp": "口を開けてください。",
        "phraseRomaji": "Kuchi o akete kudasai.",
        "phraseEs": "Abra la boca por favor.",
        "image": "../images-chosen/口.png"
    },
    {
        "kanji": "校",
        "anki_furigana": "校[こう]",
        "level": "N5",
        "meaning": "Escuela",
        "romaji": "KOU",
        "type": "nom.",
        "phraseJp": "学校へ行きます。",
        "phraseRomaji": "Gakkou e ikimasu.",
        "phraseEs": "Voy a la escuela.",
        "image": "../images-chosen/校.png"
    },
    {
        "kanji": "左",
        "anki_furigana": "左[ひだり]",
        "level": "N5",
        "meaning": "Izquierda",
        "romaji": "HIDARI",
        "type": "nom.",
        "phraseJp": "左を見てください。",
        "phraseRomaji": "Hidari o mite kudasai.",
        "phraseEs": "Mire a la izquierda.",
        "image": "../images-chosen/左.png"
    },
    {
        "kanji": "三",
        "anki_furigana": "三[さん]",
        "level": "N5",
        "meaning": "Tres",
        "romaji": "SAN",
        "type": "nom.",
        "phraseJp": "三つあります。",
        "phraseRomaji": "Mittsu arimasu.",
        "phraseEs": "Hay tres.",
        "image": "../images-chosen/三.png"
    },
    {
        "kanji": "山",
        "anki_furigana": "山[やま]",
        "level": "N5",
        "meaning": "Montaña",
        "romaji": "YAMA",
        "type": "nom.",
        "phraseJp": "山に登ります。",
        "phraseRomaji": "Yama ni noborimasu.",
        "phraseEs": "Subo a la montaña.",
        "image": "../images-chosen/山.png"
    },
    {
        "kanji": "子",
        "anki_furigana": "子[こ]",
        "level": "N5",
        "meaning": "Niño",
        "romaji": "KO",
        "type": "nom.",
        "phraseJp": "子供が遊んでいます。",
        "phraseRomaji": "Kodomo ga asonde imasu.",
        "phraseEs": "El niño está jugando.",
        "image": "../images-chosen/子.png"
    },
    {
        "kanji": "四",
        "anki_furigana": "四[よん]",
        "level": "N5",
        "meaning": "Cuatro",
        "romaji": "YON",
        "type": "nom.",
        "phraseJp": "四時に会いましょう。",
        "phraseRomaji": "Yonji ni aimashou.",
        "phraseEs": "Nos vemos a las cuatro.",
        "image": "../images-chosen/四.png"
    },
    {
        "kanji": "糸",
        "anki_furigana": "糸[いと]",
        "level": "N5",
        "meaning": "Hilo",
        "romaji": "ITO",
        "type": "nom.",
        "phraseJp": "糸を通します。",
        "phraseRomaji": "Ito o tooshimasu.",
        "phraseEs": "Paso el hilo.",
        "image": "../images-chosen/糸.png"
    },
    {
        "kanji": "字",
        "anki_furigana": "字[じ]",
        "level": "N5",
        "meaning": "Letra",
        "romaji": "JI",
        "type": "nom.",
        "phraseJp": "漢字を書きます。",
        "phraseRomaji": "Kanji o kakimasu.",
        "phraseEs": "Escribo Kanji.",
        "image": "../images-chosen/字.png"
    },
    {
        "kanji": "耳",
        "anki_furigana": "耳[みみ]",
        "level": "N5",
        "meaning": "Oreja",
        "romaji": "MIMI",
        "type": "nom.",
        "phraseJp": "耳が痛いです。",
        "phraseRomaji": "Mimi ga itai desu.",
        "phraseEs": "Me duele la oreja.",
        "image": "../images-chosen/耳.png"
    },
    {
        "kanji": "七",
        "anki_furigana": "七[なな]",
        "level": "N5",
        "meaning": "Siete",
        "romaji": "NANA",
        "type": "nom.",
        "phraseJp": "七月七日です。",
        "phraseRomaji": "Shichigatsu nanoka desu.",
        "phraseEs": "Es el 7 de julio.",
        "image": "../images-chosen/七.png"
    },
    {
        "kanji": "車",
        "anki_furigana": "車[くるま]",
        "level": "N5",
        "meaning": "Coche",
        "romaji": "KURUMA",
        "type": "nom.",
        "phraseJp": "車で行きます。",
        "phraseRomaji": "Kuruma de ikimasu.",
        "phraseEs": "Voy en coche.",
        "image": "../images-chosen/車.png"
    },
    {
        "kanji": "手",
        "anki_furigana": "手[て]",
        "level": "N5",
        "meaning": "Mano",
        "romaji": "TE",
        "type": "nom.",
        "phraseJp": "手を洗ってください。",
        "phraseRomaji": "Te o aratte kudasai.",
        "phraseEs": "Lávate las manos.",
        "image": "../images-chosen/手.png"
    },
    {
        "kanji": "十",
        "anki_furigana": "十[じゅう]",
        "level": "N5",
        "meaning": "Diez",
        "romaji": "JUU",
        "type": "nom.",
        "phraseJp": "十円あります。",
        "phraseRomaji": "Juuen arimasu.",
        "phraseEs": "Hay diez yenes.",
        "image": "../images-chosen/十.png"
    },
    {
        "kanji": "出",
        "anki_furigana": "出[で]る",
        "level": "N5",
        "meaning": "Salir",
        "romaji": "DERU",
        "type": "ver.",
        "phraseJp": "家を出ます。",
        "phraseRomaji": "Ie o demasu.",
        "phraseEs": "Salgo de casa.",
        "image": "../images-chosen/出.png"
    },
    {
        "kanji": "女",
        "anki_furigana": "女[おんな]",
        "level": "N5",
        "meaning": "Mujer",
        "romaji": "ONNA",
        "type": "nom.",
        "phraseJp": "彼女は女の人です。",
        "phraseRomaji": "Kanojo wa onna no hito desu.",
        "phraseEs": "Ella es una mujer.",
        "image": "../images-chosen/女.png"
    },
    {
        "kanji": "小",
        "anki_furigana": "小[ちい]さい",
        "level": "N5",
        "meaning": "Pequeño",
        "romaji": "CHIISAI",
        "type": "adj.",
        "phraseJp": "家は小さいです。",
        "phraseRomaji": "Ie wa chiisai desu.",
        "phraseEs": "La casa es pequeña.",
        "image": "../images-chosen/小.png"
    },
    {
        "kanji": "上",
        "anki_furigana": "上[あ]がる",
        "level": "N5",
        "meaning": "Arriba",
        "romaji": "UE",
        "type": "ver.",
        "phraseJp": "上にあります。",
        "phraseRomaji": "Ue ni arimasu.",
        "phraseEs": "Está arriba.",
        "image": "../images-chosen/上.png"
    },
    {
        "kanji": "森",
        "anki_furigana": "森[もり]",
        "level": "N5",
        "meaning": "Bosque",
        "romaji": "MORI",
        "type": "nom.",
        "phraseJp": "森は広いです。",
        "phraseRomaji": "Mori wa hiroi desu.",
        "phraseEs": "El bosque es grande.",
        "image": "../images-chosen/森.png"
    },
    {
        "kanji": "人",
        "anki_furigana": "人[ひと]",
        "level": "N5",
        "meaning": "Persona",
        "romaji": "HITO",
        "type": "nom.",
        "phraseJp": "いい人ですね。",
        "phraseRomaji": "Ii hito desu ne.",
        "phraseEs": "Es una buena persona.",
        "image": "../images-chosen/人.png"
    },
    {
        "kanji": "水",
        "anki_furigana": "水[みず]",
        "level": "N5",
        "meaning": "Agua",
        "romaji": "MIZU",
        "type": "nom.",
        "phraseJp": "水を飲みます。",
        "phraseRomaji": "Mizu o nomimasu.",
        "phraseEs": "Bebo agua.",
        "image": "../images-chosen/水.png"
    },
    {
        "kanji": "正",
        "anki_furigana": "正[ただ]しい",
        "level": "N5",
        "meaning": "Correcto",
        "romaji": "TADASHII",
        "type": "adj.",
        "phraseJp": "正しい答えです。",
        "phraseRomaji": "Tadashii kotae desu.",
        "phraseEs": "Es la respuesta correcta.",
        "image": "../images-chosen/正.png"
    },
    {
        "kanji": "生",
        "anki_furigana": "生[い]きる",
        "level": "N5",
        "meaning": "Vivir",
        "romaji": "IKIRU",
        "type": "ver.",
        "phraseJp": "元気に生きます。",
        "phraseRomaji": "Genki ni ikimasu.",
        "phraseEs": "Vivo con energía.",
        "image": "../images-chosen/生.png"
    },
    {
        "kanji": "青",
        "anki_furigana": "青[あお]い",
        "level": "N5",
        "meaning": "Azul",
        "romaji": "AOI",
        "type": "adj.",
        "phraseJp": "青い空です。",
        "phraseRomaji": "Aoi sora desu.",
        "phraseEs": "Es un cielo azul.",
        "image": "../images-chosen/青.png"
    },
    {
        "kanji": "夕",
        "anki_furigana": "夕[ゆう]",
        "level": "N5",
        "meaning": "Tarde",
        "romaji": "YUU",
        "type": "nom.",
        "phraseJp": "夕日が綺麗です。",
        "phraseRomaji": "Yuuhi ga kirei desu.",
        "phraseEs": "El atardecer es bonito.",
        "image": "../images-chosen/夕.png"
    },
    {
        "kanji": "石",
        "anki_furigana": "石[いし]",
        "level": "N5",
        "meaning": "Piedra",
        "romaji": "ISHI",
        "type": "nom.",
        "phraseJp": "石を投げないで。",
        "phraseRomaji": "Ishi o naganaide.",
        "phraseEs": "No tires piedras.",
        "image": "../images-chosen/石.png"
    },
    {
        "kanji": "赤",
        "anki_furigana": "赤[あか]い",
        "level": "N5",
        "meaning": "Rojo",
        "romaji": "AKAI",
        "type": "adj.",
        "phraseJp": "赤いリンゴです。",
        "phraseRomaji": "Akai ringo desu.",
        "phraseEs": "Es una manzana roja.",
        "image": "../images-chosen/赤.png"
    },
    {
        "kanji": "千",
        "anki_furigana": "千[せん]",
        "level": "N5",
        "meaning": "Mil",
        "romaji": "SEN",
        "type": "nom.",
        "phraseJp": "千円札です。",
        "phraseRomaji": "Sen en satsu desu.",
        "phraseEs": "Es un billete de mil yenes.",
        "image": "../images-chosen/千.png"
    },
    {
        "kanji": "川",
        "anki_furigana": "川[かわ]",
        "level": "N5",
        "meaning": "Río",
        "romaji": "KAWA",
        "type": "nom.",
        "phraseJp": "川が流れています。",
        "phraseRomaji": "Kawa ga nagarete imasu.",
        "phraseEs": "El río fluye.",
        "image": "../images-chosen/川.png"
    },
    {
        "kanji": "先",
        "anki_furigana": "先[さき]",
        "level": "N5",
        "meaning": "Anterior",
        "romaji": "SAKI",
        "type": "nom.",
        "phraseJp": "先生に聞きます。",
        "phraseRomaji": "Sensei ni kikimasu.",
        "phraseEs": "Le pregunto al profesor.",
        "image": "../images-chosen/先.png"
    },
    {
        "kanji": "早",
        "anki_furigana": "早[はや]い",
        "level": "N5",
        "meaning": "Temprano",
        "romaji": "HAYAI",
        "type": "adj.",
        "phraseJp": "朝早いです。",
        "phraseRomaji": "Asa hayai desu.",
        "phraseEs": "Es temprano en la mañana.",
        "image": "../images-chosen/早.png"
    },
    {
        "kanji": "草",
        "anki_furigana": "草[くさ]",
        "level": "N5",
        "meaning": "Hierba",
        "romaji": "KUSA",
        "type": "nom.",
        "phraseJp": "草を刈ります。",
        "phraseRomaji": "Kusa o karimasu.",
        "phraseEs": "Corto la hierba.",
        "image": "../images-chosen/草.png"
    },
    {
        "kanji": "足",
        "anki_furigana": "足[あし]",
        "level": "N5",
        "meaning": "Pie",
        "romaji": "ASHI",
        "type": "nom.",
        "phraseJp": "足が長いです。",
        "phraseRomaji": "Ashi ga nagai desu.",
        "phraseEs": "Tiene piernas largas.",
        "image": "../images-chosen/足.png"
    },
    {
        "kanji": "村",
        "anki_furigana": "村[むら]",
        "level": "N5",
        "meaning": "Pueblo",
        "romaji": "MURA",
        "type": "nom.",
        "phraseJp": "小さな村です。",
        "phraseRomaji": "Chiisana mura desu.",
        "phraseEs": "Es un pueblo pequeño.",
        "image": "../images-chosen/村.png"
    },
    {
        "kanji": "大",
        "anki_furigana": "大[おお]きい",
        "level": "N5",
        "meaning": "Grande",
        "romaji": "OOKII",
        "type": "adj.",
        "phraseJp": "大きな家です。",
        "phraseRomaji": "Ookina ie desu.",
        "phraseEs": "Es una casa grande.",
        "image": "../images-chosen/大.png"
    },
    {
        "kanji": "男",
        "anki_furigana": "男[おとこ]",
        "level": "N5",
        "meaning": "Hombre",
        "romaji": "OTOKO",
        "type": "nom.",
        "phraseJp": "男の子です。",
        "phraseRomaji": "Otoko no ko desu.",
        "phraseEs": "Es un niño.",
        "image": "../images-chosen/男.png"
    },
    {
        "kanji": "竹",
        "anki_furigana": "竹[たけ]",
        "level": "N5",
        "meaning": "Bambú",
        "romaji": "TAKE",
        "type": "nom.",
        "phraseJp": "竹林があります。",
        "phraseRomaji": "Chikurin ga arimasu.",
        "phraseEs": "Hay un bosque de bambú.",
        "image": "../images-chosen/竹.png"
    },
    {
        "kanji": "中",
        "anki_furigana": "中[なか]",
        "level": "N5",
        "meaning": "Dentro",
        "romaji": "NAKA",
        "type": "nom.",
        "phraseJp": "箱の中にあります。",
        "phraseRomaji": "Hako no naka ni arimasu.",
        "phraseEs": "Está dentro de la caja.",
        "image": "../images-chosen/中.png"
    },
    {
        "kanji": "虫",
        "anki_furigana": "虫[むし]",
        "level": "N5",
        "meaning": "Insecto",
        "romaji": "MUSHI",
        "type": "nom.",
        "phraseJp": "虫が飛んでいます。",
        "phraseRomaji": "Mushi ga tonde imasu.",
        "phraseEs": "Un insecto vuela.",
        "image": "../images-chosen/虫.png"
    },
    {
        "kanji": "町",
        "anki_furigana": "町[まち]",
        "level": "N5",
        "meaning": "Ciudad",
        "romaji": "MACHI",
        "type": "nom.",
        "phraseJp": "町へ行きます。",
        "phraseRomaji": "Machi e ikimasu.",
        "phraseEs": "Voy a la ciudad.",
        "image": "../images-chosen/町.png"
    },
    {
        "kanji": "天",
        "anki_furigana": "天[てん]",
        "level": "N5",
        "meaning": "Cielo",
        "romaji": "TEN",
        "type": "nom.",
        "phraseJp": "天気予報です。",
        "phraseRomaji": "Tenki yohou desu.",
        "phraseEs": "Es el pronóstico del tiempo.",
        "image": "../images-chosen/天.png"
    },
    {
        "kanji": "田",
        "anki_furigana": "田[た]",
        "level": "N5",
        "meaning": "Campo",
        "romaji": "TA",
        "type": "nom.",
        "phraseJp": "田んぼがあります。",
        "phraseRomaji": "Tanbo ga arimasu.",
        "phraseEs": "Hay un campo de arroz.",
        "image": "../images-chosen/田.png"
    },
    {
        "kanji": "土",
        "anki_furigana": "土[つち]",
        "level": "N5",
        "meaning": "Tierra",
        "romaji": "TSUCHI",
        "type": "nom.",
        "phraseJp": "土を掘ります。",
        "phraseRomaji": "Tsuchi o horimasu.",
        "phraseEs": "Cavo la tierra.",
        "image": "../images-chosen/土.png"
    },
    {
        "kanji": "二",
        "anki_furigana": "二[に]",
        "level": "N5",
        "meaning": "Dos",
        "romaji": "NI",
        "type": "nom.",
        "phraseJp": "二時間かかります。",
        "phraseRomaji": "Nijikan kakarimasu.",
        "phraseEs": "Tarda dos horas.",
        "image": "../images-chosen/二.png"
    },
    {
        "kanji": "日",
        "anki_furigana": "日[ひ]",
        "level": "N5",
        "meaning": "Sol/Día",
        "romaji": "HI",
        "type": "nom.",
        "phraseJp": "日曜日です。",
        "phraseRomaji": "Nichiyoubi desu.",
        "phraseEs": "Es domingo.",
        "image": "../images-chosen/日.png"
    },
    {
        "kanji": "入",
        "anki_furigana": "入[はい]る",
        "level": "N5",
        "meaning": "Entrar",
        "romaji": "HAIRU",
        "type": "ver.",
        "phraseJp": "中に入ってください。",
        "phraseRomaji": "Naka ni haitte kudasai.",
        "phraseEs": "Entre por favor.",
        "image": "../images-chosen/入.png"
    },
    {
        "kanji": "年",
        "anki_furigana": "年[とし]",
        "level": "N5",
        "meaning": "Año",
        "romaji": "TOSHI",
        "type": "nom.",
        "phraseJp": "去年行きました。",
        "phraseRomaji": "Kyonen ikimashita.",
        "phraseEs": "Fui el año pasado.",
        "image": "../images-chosen/年.png"
    },
    {
        "kanji": "白",
        "anki_furigana": "白[しろ]い",
        "level": "N5",
        "meaning": "Blanco",
        "romaji": "SHIROI",
        "type": "adj.",
        "phraseJp": "白い犬です。",
        "phraseRomaji": "Shiroi inu desu.",
        "phraseEs": "Es un perro blanco.",
        "image": "../images-chosen/白.png"
    },
    {
        "kanji": "八",
        "anki_furigana": "八[はち]",
        "level": "N5",
        "meaning": "Ocho",
        "romaji": "HACHI",
        "type": "nom.",
        "phraseJp": "八つあります。",
        "phraseRomaji": "Yattsu arimasu.",
        "phraseEs": "Hay ocho.",
        "image": "../images-chosen/八.png"
    },
    {
        "kanji": "百",
        "anki_furigana": "百[ひゃく]",
        "level": "N5",
        "meaning": "Cien",
        "romaji": "HYAKU",
        "type": "nom.",
        "phraseJp": "百円です。",
        "phraseRomaji": "Hyaku en desu.",
        "phraseEs": "Son cien yenes.",
        "image": "../images-chosen/百.png"
    },
    {
        "kanji": "文",
        "anki_furigana": "文[ぶん]",
        "level": "N5",
        "meaning": "Escritura",
        "romaji": "BUN",
        "type": "nom.",
        "phraseJp": "文章を書きます。",
        "phraseRomaji": "Bunshou o kakimasu.",
        "phraseEs": "Escribo un texto.",
        "image": "../images-chosen/文.png"
    },
    {
        "kanji": "木",
        "anki_furigana": "木[き]",
        "level": "N5",
        "meaning": "Árbol",
        "romaji": "KI",
        "type": "nom.",
        "phraseJp": "木の下で休みます。",
        "phraseRomaji": "Ki no shita de yasumimasu.",
        "phraseEs": "Descanso bajo el árbol.",
        "image": "../images-chosen/木.png"
    },
    {
        "kanji": "本",
        "anki_furigana": "本[ほん]",
        "level": "N5",
        "meaning": "Libro",
        "romaji": "HON",
        "type": "nom.",
        "phraseJp": "本を読みます。",
        "phraseRomaji": "Hon o yomimasu.",
        "phraseEs": "Leo un libro.",
        "image": "../images-chosen/本.png"
    },
    {
        "kanji": "名",
        "anki_furigana": "名[な]",
        "level": "N5",
        "meaning": "nom.",
        "romaji": "NAMAE",
        "type": "nom.",
        "phraseJp": "名前を書いてください。",
        "phraseRomaji": "Namae o kaite kudasai.",
        "phraseEs": "Escriba su nom..",
        "image": "../images-chosen/名.png"
    },
    {
        "kanji": "目",
        "anki_furigana": "目[め]",
        "level": "N5",
        "meaning": "Ojo",
        "romaji": "ME",
        "type": "nom.",
        "phraseJp": "目が大きいです。",
        "phraseRomaji": "Me ga ookii desu.",
        "phraseEs": "Tiene los ojos grandes.",
        "image": "../images-chosen/目.png"
    },
    {
        "kanji": "立",
        "anki_furigana": "立[た]つ",
        "level": "N5",
        "meaning": "Levantarse",
        "romaji": "TATSU",
        "type": "ver.",
        "phraseJp": "立ってください。",
        "phraseRomaji": "Tatte kudasai.",
        "phraseEs": "Levántese por favor.",
        "image": "../images-chosen/立.png"
    },
    {
        "kanji": "力",
        "anki_furigana": "力[ちから]",
        "level": "N5",
        "meaning": "Poder",
        "romaji": "CHIKARA",
        "type": "nom.",
        "phraseJp": "力持ちですね。",
        "phraseRomaji": "Chikaramochi desu ne.",
        "phraseEs": "Es fuerte.",
        "image": "../images-chosen/力.png"
    },
    {
        "kanji": "林",
        "anki_furigana": "林[はやし]",
        "level": "N5",
        "meaning": "Arboleda",
        "romaji": "HAYASHI",
        "type": "nom.",
        "phraseJp": "林を歩きます。",
        "phraseRomaji": "Hayashi o arukimasu.",
        "phraseEs": "Camino por la arboleda.",
        "image": "../images-chosen/林.png"
    },
    {
        "kanji": "六",
        "anki_furigana": "六[ろく]",
        "level": "N5",
        "meaning": "Seis",
        "romaji": "ROKU",
        "type": "nom.",
        "phraseJp": "六人家族です。",
        "phraseRomaji": "Rokunin kazoku desu.",
        "phraseEs": "Somos una familia de seis.",
        "image": "../images-chosen/六.png"
    }
];
