import csv

# This script enriches the kanjis-80.csv with meanings and example phrases.

data = [
    ["一", "nombre", "no", "", "一[いち]", "Uno", "ICHI", "一から始めましょう。", "Ichi kara hajimemashou.", "Empecemos desde uno."],
    ["右", "nombre", "no", "", "右[みぎ]", "Derecha", "MIGI", "右に曲がってください。", "Migi ni magatte kudasai.", "Gire a la derecha."],
    ["雨", "nombre", "no", "", "雨[あめ]", "Lluvia", "AME", "雨が降っています。", "Ame ga futte imasu.", "Está lloviendo."],
    ["円", "nombre", "no", "", "円[えん]", "Yen", "EN", "千円あります。", "Sen en arimasu.", "Tengo mil yenes."],
    ["王", "nombre", "no", "", "王[おう]", "Rey", "OU", "王様は城にいます。", "Ousama wa shiro ni imasu.", "El rey está en el castillo."],
    ["音", "nombre", "no", "", "音[おと]", "Sonido", "OTO", "いい音ですね。", "Ii oto desu ne.", "Es un buen sonido."],
    ["下", "nombre/verbo", "sí", "る", "下[くだ]る", "Abajo", "SHITA", "下に降りてください。", "Shita ni orite kudasai.", "Baje por favor."],
    ["火", "nombre", "no", "", "火[ひ]", "Fuego", "HI", "火を消してください。", "Hi o keshite kudasai.", "Apague el fuego."],
    ["花", "nombre", "no", "", "花[はな]", "Flor", "HANA", "花が咲きました。", "Hana ga sakimashita.", "La flor floreció."],
    ["貝", "nombre", "no", "", "貝[かい]", "Marisco", "KAI", "貝を食べます。", "Kai o tabemasu.", "Como mariscos."],
    ["学", "nombre/verbo", "sí", "ぶ", "学[まな]ぶ", "Estudio", "GAKU", "日本語を学びます。", "Nihongo o manabimasu.", "Estudio japonés."],
    ["気", "nombre", "no", "", "気[き]", "Espíritu", "KI", "お元気ですか？", "Ogenki desu ka?", "¿Cómo estás?"],
    ["九", "nombre", "no", "", "九[きゅう]", "Nueve", "KYUU", "九時です。", "Kyuuji desu.", "Son las nueve."],
    ["休", "nombre/verbo", "sí", "む", "休[やす]む", "Descanso", "YASUMU", "ちょっと休みましょう。", "Chotto yasumimashou.", "Descansemos un poco."],
    ["玉", "nombre", "no", "", "玉[たま]", "Joya/Bola", "TAMA", "玉ねぎを買います。", "Tamanegi o kaimasu.", "Compro cebollas."],
    ["金", "nombre", "no", "", "金[かね]", "Dinero", "KANE", "お金がありません。", "Okane ga arimasen.", "No tengo dinero."],
    ["空", "nombre", "no", "", "空[そら]", "Cielo", "SORA", "空が青いです。", "Sora ga aoi desu.", "El cielo está azul."],
    ["月", "nombre", "no", "", "月[つき]", "Luna", "TSUKI", "月が綺麗ですね。", "Tsuki ga kirei desu ne.", "La luna está bonita."],
    ["犬", "nombre", "no", "", "犬[いぬ]", "Perro", "INU", "犬を飼っています。", "Inu o katte imasu.", "Tengo un perro."],
    ["見", "verbo", "sí", "る", "見[み]る", "Ver", "MIRU", "テレビを見ます。", "Terebi o mimasu.", "Veo la televisión."],
    ["五", "nombre", "no", "", "五[ご]", "Cinco", "GO", "五人います。", "Gonin imasu.", "Hay cinco personas."],
    ["口", "nombre", "no", "", "口[くち]", "Boca", "KUCHI", "口を開けてください。", "Kuchi o akete kudasai.", "Abra la boca por favor."],
    ["校", "nombre", "no", "", "校[こう]", "Escuela", "KOU", "学校へ行きます。", "Gakkou e ikimasu.", "Voy a la escuela."],
    ["左", "nombre", "no", "", "左[ひだり]", "Izquierda", "HIDARI", "左を見てください。", "Hidari o mite kudasai.", "Mire a la izquierda."],
    ["三", "nombre", "no", "", "三[さん]", "Tres", "SAN", "三つあります。", "Mittsu arimasu.", "Hay tres."],
    ["山", "nombre", "no", "", "山[やま]", "Montaña", "YAMA", "山に登ります。", "Yama ni noborimasu.", "Subo a la montaña."],
    ["子", "nombre", "no", "", "子[こ]", "Niño", "KO", "子供が遊んでいます。", "Kodomo ga asonde imasu.", "El niño está jugando."],
    ["四", "nombre", "no", "", "四[よん]", "Cuatro", "YON", "四時に会いましょう。", "Yonji ni aimashou.", "Nos vemos a las cuatro."],
    ["糸", "nombre", "no", "", "糸[いと]", "Hilo", "ITO", "糸を通します。", "Ito o tooshimasu.", "Paso el hilo."],
    ["字", "nombre", "no", "", "字[じ]", "Letra", "JI", "漢字を書きます。", "Kanji o kakimasu.", "Escribo Kanji."],
    ["耳", "nombre", "no", "", "耳[みみ]", "Oreja", "MIMI", "耳が痛いです。", "Mimi ga itai desu.", "Me duele la oreja."],
    ["七", "nombre", "no", "", "七[なな]", "Siete", "NANA", "七月七日です。", "Shichigatsu nanoka desu.", "Es el 7 de julio."],
    ["車", "nombre", "no", "", "車[くるま]", "Coche", "KURUMA", "車で行きます。", "Kuruma de ikimasu.", "Voy en coche."],
    ["手", "nombre", "no", "", "手[て]", "Mano", "TE", "手を洗ってください。", "Te o aratte kudasai.", "Lávate las manos."],
    ["十", "nombre", "no", "", "十[じゅう]", "Diez", "JUU", "十円あります。", "Juuen arimasu.", "Hay diez yenes."],
    ["出", "verbo", "sí", "る", "出[で]る", "Salir", "DERU", "家を出ます。", "Ie o demasu.", "Salgo de casa."],
    ["女", "nombre", "no", "", "女[おんな]", "Mujer", "ONNA", "彼女は女の人です。", "Kanojo wa onna no hito desu.", "Ella es una mujer."],
    ["小", "adjetivo", "sí", "さい", "小[ちい]さい", "Pequeño", "CHIISAI", "家は小さいです。", "Ie wa chiisai desu.", "La casa es pequeña."],
    ["上", "nombre/verbo", "sí", "がる", "上[あ]がる", "Arriba", "UE", "上にあります。", "Ue ni arimasu.", "Está arriba."],
    ["森", "nombre", "no", "", "森[もり]", "Bosque", "MORI", "森は広いです。", "Mori wa hiroi desu.", "El bosque es grande."],
    ["人", "nombre", "no", "", "人[ひと]", "Persona", "HITO", "いい人ですね。", "Ii hito desu ne.", "Es una buena persona."],
    ["水", "nombre", "no", "", "水[みず]", "Agua", "MIZU", "水を飲みます。", "Mizu o nomimasu.", "Bebo agua."],
    ["正", "nombre/adjetivo", "sí", "しい", "正[ただ]しい", "Correcto", "TADASHII", "正しい答えです。", "Tadashii kotae desu.", "Es la respuesta correcta."],
    ["生", "verbo", "sí", "きる", "生[い]きる", "Vivir", "IKIRU", "元気に生きます。", "Genki ni ikimasu.", "Vivo con energía."],
    ["青", "nombre/adjetivo", "sí", "い", "青[あお]い", "Azul", "AOI", "青い空です。", "Aoi sora desu.", "Es un cielo azul."],
    ["夕", "nombre", "no", "", "夕[ゆう]", "Tarde", "YUU", "夕日が綺麗です。", "Yuuhi ga kirei desu.", "El atardecer es bonito."],
    ["石", "nombre", "no", "", "石[いし]", "Piedra", "ISHI", "石を投げないで。", "Ishi o naganaide.", "No tires piedras."],
    ["赤", "nombre/adjetivo", "sí", "い", "赤[あか]い", "Rojo", "AKAI", "赤いリンゴです。", "Akai ringo desu.", "Es una manzana roja."],
    ["千", "nombre", "no", "", "千[せん]", "Mil", "SEN", "千円札です。", "Sen en satsu desu.", "Es un billete de mil yenes."],
    ["川", "nombre", "no", "", "川[かわ]", "Río", "KAWA", "川が流れています。", "Kawa ga nagarete imasu.", "El río fluye."],
    ["先", "nombre", "no", "", "先[さき]", "Anterior", "SAKI", "先生に聞きます。", "Sensei ni kikimasu.", "Le pregunto al profesor."],
    ["早", "adjetivo", "sí", "い", "早[はや]い", "Temprano", "HAYAI", "朝早いです。", "Asa hayai desu.", "Es temprano en la mañana."],
    ["草", "nombre", "no", "", "草[くさ]", "Hierba", "KUSA", "草を刈ります。", "Kusa o karimasu.", "Corto la hierba."],
    ["足", "nombre", "no", "", "足[あし]", "Pie", "ASHI", "足が長いです。", "Ashi ga nagai desu.", "Tiene piernas largas."],
    ["村", "nombre", "no", "", "村[むら]", "Pueblo", "MURA", "小さな村です。", "Chiisana mura desu.", "Es un pueblo pequeño."],
    ["大", "adjetivo", "sí", "きい", "大[おお]きい", "Grande", "OOKII", "大きな家です。", "Ookina ie desu.", "Es una casa grande."],
    ["男", "nombre", "no", "", "男[おとこ]", "Hombre", "OTOKO", "男の子です。", "Otoko no ko desu.", "Es un niño."],
    ["竹", "nombre", "no", "", "竹[たけ]", "Bambú", "TAKE", "竹林があります。", "Chikurin ga arimasu.", "Hay un bosque de bambú."],
    ["中", "nombre", "no", "", "中[なか]", "Dentro", "NAKA", "箱の中にあります。", "Hako no naka ni arimasu.", "Está dentro de la caja."],
    ["虫", "nombre", "no", "", "虫[むし]", "Insecto", "MUSHI", "虫が飛んでいます。", "Mushi ga tonde imasu.", "Un insecto vuela."],
    ["町", "nombre", "no", "", "町[まち]", "Ciudad", "MACHI", "町へ行きます。", "Machi e ikimasu.", "Voy a la ciudad."],
    ["天", "nombre", "no", "", "天[てん]", "Cielo", "TEN", "天気予報です。", "Tenki yohou desu.", "Es el pronóstico del tiempo."],
    ["田", "nombre", "no", "", "田[た]", "Campo", "TA", "田んぼがあります。", "Tanbo ga arimasu.", "Hay un campo de arroz."],
    ["土", "nombre", "no", "", "土[つち]", "Tierra", "TSUCHI", "土を掘ります。", "Tsuchi o horimasu.", "Cavo la tierra."],
    ["二", "nombre", "no", "", "二[に]", "Dos", "NI", "二時間かかります。", "Nijikan kakarimasu.", "Tarda dos horas."],
    ["日", "nombre", "no", "", "日[ひ]", "Sol/Día", "HI", "日曜日です。", "Nichiyoubi desu.", "Es domingo."],
    ["入", "verbo", "sí", "る", "入[はい]る", "Entrar", "HAIRU", "中に入ってください。", "Naka ni haitte kudasai.", "Entre por favor."],
    ["年", "nombre", "no", "", "年[とし]", "Año", "TOSHI", "去年行きました。", "Kyonen ikimashita.", "Fui el año pasado."],
    ["白", "nombre/adjetivo", "sí", "い", "白[しろ]い", "Blanco", "SHIROI", "白い犬です。", "Shiroi inu desu.", "Es un perro blanco."],
    ["八", "nombre", "no", "", "八[はち]", "Ocho", "HACHI", "八つあります。", "Yattsu arimasu.", "Hay ocho."],
    ["百", "nombre", "no", "", "百[ひゃく]", "Cien", "HYAKU", "百円です。", "Hyaku en desu.", "Son cien yenes."],
    ["文", "nombre", "no", "", "文[ぶん]", "Escritura", "BUN", "文章を書きます。", "Bunshou o kakimasu.", "Escribo un texto."],
    ["木", "nombre", "no", "", "木[き]", "Árbol", "KI", "木の下で休みます。", "Ki no shita de yasumimasu.", "Descanso bajo el árbol."],
    ["本", "nombre", "no", "", "本[ほん]", "Libro", "HON", "本を読みます。", "Hon o yomimasu.", "Leo un libro."],
    ["名", "nombre", "no", "", "名[な]", "Nombre", "NAMAE", "名前を書いてください。", "Namae o kaite kudasai.", "Escriba su nombre."],
    ["目", "nombre", "no", "", "目[め]", "Ojo", "ME", "目が大きいです。", "Me ga ookii desu.", "Tiene los ojos grandes."],
    ["立", "verbo", "sí", "つ", "立[た]つ", "Levantarse", "TATSU", "立ってください。", "Tatte kudasai.", "Levántese por favor."],
    ["力", "nombre", "no", "", "力[ちから]", "Poder", "CHIKARA", "力持ちですね。", "Chikaramochi desu ne.", "Es fuerte."],
    ["林", "nombre", "no", "", "林[はやし]", "Arboleda", "HAYASHI", "林を歩きます。", "Hayashi o arukimasu.", "Camino por la arboleda."],
    ["六", "nombre", "no", "", "六[ろく]", "Seis", "ROKU", "六人家族です。", "Rokunin kazoku desu.", "Somos una familia de seis."]
]

header = ["Kanji", "Tipo", "Requiere Hiragana", "Hiragana Extra", "Anki Furigana", "Meaning", "Romaji", "PhraseJp", "PhraseRomaji", "PhraseEs"]

with open("data/kanjis-80.csv", "w", encoding="utf-8", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(data)

print("Enriched kanjis-80.csv successfully.")
